# Generated by Django 5.0.4 on 2024-05-04 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Smartphone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=200)),
                ('price_final', models.FloatField()),
                ('old_price', models.FloatField()),
                ('discount_f', models.IntegerField()),
                ('product_url', models.URLField()),
            ],
        ),
    ]
